apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: test-ca-cluster-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/server-snippet: |-
      location /ready-for-deploy {
        return 403;
      }
      location /prepare-for-deploy {
        return 403;
      }
spec:
  ingressClassName: nginx
  rules:
  - host: test-phrase.reisei.ru
    http:
      paths:
      - backend:
          service:
            name: phrase
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - test-phrase.reisei.ru
    secretName: basic-ingress-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-with-auth
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  ingressClassName: nginx
  rules:
  - host: test-phrase.reisei.ru
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: phrase
            port:
              number: 80
  tls:
  - hosts:
    - test-phrase.reisei.ru
    secretName: basic-ingress-cert
