replicaCount: 2

image:
  repository: localhost:32000/phrase
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources:
  limits: 
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

redis:
  architecture: standalone

postgresql:
  auth:
    username: phrase
    password: qwerty
    database: phrase
