name: Docker Build 

on:
  push:
    paths:
      - 'src/**'
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t localhost:32000/phrase:${{ github.sha }} .


      - name: Push Docker Image
        run: docker push localhost:32000/phrase:${{ github.sha }}

