name: Docker Build 

on:
  push:
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'charts/**'
      - '.github/**'
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t localhost:32000/phrase:${{ github.sha }} .

      - name: Tag as the latest
        run: docker tag localhost:32000/phrase:${{ github.sha }} localhost:32000/phrase:latest


      - name: Push Docker Image w Version
        run: docker push localhost:32000/phrase:${{ github.sha }}

      - name: Push Docker Latest Image
        run: docker push localhost:32000/phrase:latest

  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Install/Upgrade helm chart
        run: helm upgrade phrase ./charts/phrase --install --namespace phrase --create-namespace --set image.tag=${{ github.sha }}
